CREATE TABLE IF NOT EXISTS "chip" (
    id TEXT PRIMARY KEY NOT NULL,
    label TEXT NOT NULL,
    value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "report_to_chip" (
    id TEXT PRIMARY KEY NOT NULL,
    report_id TEXT NOT NULL REFERENCES report(id) ON DELETE CASCADE,
    chip_id TEXT NOT NULL REFERENCES chip(id) ON DELETE CASCADE
);

ALTER TABLE
    "chip" ENABLE ELECTRIC;

ALTER TABLE
    "report_to_chip" ENABLE ELECTRIC;