
CREATE TABLE clause(
   key     text NOT NULL 
  ,value   text NOT NULL
  ,udap_id text
  ,text    text NOT NULL
  , PRIMARY KEY (key, value, udap_id)
);

INSERT INTO clause(key,value,udap_id,text) VALUES ('demandeur','Particulier','ALL','Vous avez rencontré un agent de l’UDAP car votre projet se situe dans un espace protégé pour son patrimoine. Cet agent évalue si votre projet peut s’intégrer à cet espace. Ce jugement ne remplace pas les demandes d’autorisation de travaux. Ci-dessous le compte rendu de l’échange :');
INSERT INTO clause(key,value,udap_id,text) VALUES ('demandeur','Maître d''oeuvre','ALL','Vous avez rencontré un agent de l’UDAP car votre projet se situe dans un espace protégé pour son patrimoine. Le jugement émis ne remplace pas les demandes d’autorisation de travaux. Si la décision est favorable, vous devrez contacter le service instructeur. Notez que le maître d’œuvre sera notre interlocuteur privilégié pour ce projet. Ci-dessous le compte rendu de l’échange :');
INSERT INTO clause(key,value,udap_id,text) VALUES ('demandeur','Collectivité','ALL','Vous avez rencontré un agent de l’UDAP car votre projet se situe dans un espace protégé pour son patrimoine. Cet agent évalue si votre projet peut s’intégrer à cet espace. Le jugement émis ne remplace pas les demandes d’autorisation de travaux. Si la décision est favorable, vous devrez contacter le service instructeur. Ci-dessous le compte rendu de l’échange :');
INSERT INTO clause(key,value,udap_id,text) VALUES ('demandeur','Service de l''État','ALL','Vous avez rencontré un agent de l’UDAP car votre projet se situe dans un espace protégé pour son patrimoine. Dans le cadre de notre relation collégiale, l’UDAP facilitera l’application des règlements en vigueur, de la qualité architecturale et patrimoniale. Nos conseils ne remplacent pas les demandes d’autorisation de travaux. Ci-dessous le compte rendu de l’échange :');
INSERT INTO clause(key,value,udap_id,text) VALUES ('demandeur','Autre','ALL','Vous avez rencontré un agent de l’UDAP car votre projet se situe dans un espace protégé pour son patrimoine. Nos conseils ne remplacent pas les demandes d’autorisation de travaux. Ci-dessous le compte rendu de l’échange :');

INSERT INTO clause(key,value,udap_id,text) VALUES ('type-espace','2Bis_SPR','ALL','Vous avez rencontré un agent de l’UDAP car votre projet se situe dans un site patrimonial remarquable (SPR). Son rôle est de contrôler la compatibilité de votre projet avec le règlement du SPR. Votre projet devra obligatoirement le respecter. Ci-dessous le compte rendu de l’échange :');
INSERT INTO clause(key,value,udap_id,text) VALUES ('type-espace','Abord','ALL','Vous avez rencontré un agent de l’UDAP car votre projet se situe aux abords d’un monument historique (MH). Son rôle est de s’assurer de la bonne intégration paysagère et architecturale de votre projet dans cet environnement. L''avis favorable de l’architecte des bâtiments de France sera obligatoire pour obtenir l’autorisation de travaux. Ci-dessous le compte rendu de l’échange :');
INSERT INTO clause(key,value,udap_id,text) VALUES ('type-espace','Périmètre','ALL','Vous avez rencontré un agent de l’UDAP car votre projet se situe proche d''un monument historique, mais sans visibilité entre l''un et l''autre. Son rôle est de s’assurer de la bonne intégration paysagère et architecturale de votre projet dans cet environnement. Il apporte un conseil pour la collectivité délivrant l’autorisation de travaux. Ci-dessous le compte rendu de l’échange :');
INSERT INTO clause(key,value,udap_id,text) VALUES ('type-espace','Site classé/DP','ALL','Vous avez rencontré un agent de l’UDAP car votre projet se situe en site classé. Il vous accompagne pour l''élaboration de votre déclaration préalable pour recevoir l’accord du préfet du département. Ci-dessous le compte rendu de l’échange :');
INSERT INTO clause(key,value,udap_id,text) VALUES ('type-espace','Site classé/PC','ALL','Vous avez rencontré un agent de l’UDAP car votre projet se situe en site classé. Il vous accompagne pour l''élaboration de votre projet pour son passage en commission départementale des sites et des paysages. L’autorisation de travaux doit recevoir l’accord du ministère de la transition écologique dans un délai de 8 mois. Il convient également de vous rapprocher de l’inspecteur de sites de la DREAL. Ci-dessous le compte rendu de l’échange :');
INSERT INTO clause(key,value,udap_id,text) VALUES ('type-espace','Site inscrit','ALL','Vous avez rencontré un agent de l’UDAP car votre projet se situe en site inscrit .Son rôle est de s’assurer de la bonne intégration paysagère et architecturale de votre projet dans cet environnement. L’avis de l’UDAP est transmis à la collectivité délivrant l’autorisation de travaux.Ci-dessous le compte rendu de l’échange :');
INSERT INTO clause(key,value,udap_id,text) VALUES ('type-espace','Monument historique classé','ALL','Vous avez rencontré un agent de l’UDAP car votre projet porte sur un monument historique classé. Son rôle est de vous accompagner dans l’élaboration de votre demande d''autorisation de travaux. Cette dernière sera transmise à la Conservation régionale des monuments historiques (CRMH) pour accord dans un délai de 6 mois. Ci-dessous le compte rendu de l’échange :');
INSERT INTO clause(key,value,udap_id,text) VALUES ('type-espace','Monument historique inscrit','ALL','Vous avez rencontré un agent de l’UDAP car votre projet porte sur un monument historique inscrit. Son rôle est de vous accompagner dans l’élaboration de votre demande d''autorisation de travaux. Cette dernière sera transmise à la Conservation régionale des monuments historiques (CRMH) pour accord dans un délai de 5 mois. Ci-dessous le compte rendu de l’échange :');

INSERT INTO clause(key,value,udap_id,text) VALUES ('decision','Oui','ALL','Suite à nos échanges, il ressort que le projet est abouti et que vous pouvez déposer une demande d''autorisation d''urbanisme.');
INSERT INTO clause(key,value,udap_id,text) VALUES ('decision','Modif. mini.','ALL','Suite à nos échanges, il ressort que le projet est assez abouti pour que vous puissiez déposer une demande d''autorisation d''urbanisme. Elle pourra donner lieu à des prescriptions ou des observations mineures.');
INSERT INTO clause(key,value,udap_id,text) VALUES ('decision','A suivre','ALL','Suite à nos échanges, il ressort que le projet appelle des observations et n’est pas au stade d’avancement nécessaire pour déposer une demande d''autorisation d''urbanisme.\nIl sera nécessaire de le représenter soit par l’intermédiaire de la collectivité si une permanence y est assurée par un agent de l’UDAP (voir le contact ci-dessous) soit via : https://www.demarches-simplifiees.fr/commencer/udap');
INSERT INTO clause(key,value,udap_id,text) VALUES ('decision','Refus SPR','ALL','Suite à nos échanges, il ressort que le projet n''est pas réalisable car il porte atteinte au site patrimonial remarquable. Si une autorisation d''urbanisme était déposée, elle serait refusée. Il convient d’intégrer la réglementation en vigueur à votre projet.\nVous pouvez présenter un nouveau projet soit par l’intermédiaire de la collectivité si une permanence y est assurée par un agent de l’UDAP (voir le contact ci-dessous) soit via : https://www.demarches-simplifiees.fr/commencer/udap');
INSERT INTO clause(key,value,udap_id,text) VALUES ('decision','Refus abords/site','ALL','Suite à nos échanges, il ressort que le projet n''est pas réalisable car il porte atteinte à l’espace protégé. Si une autorisation d''urbanisme était déposée, elle serait refusée.\nVous pouvez présenter un nouveau projet soit par l’intermédiaire de la collectivité si une permanence y est assurée par un agent de l’UDAP (voir le contact ci-dessous) soit via : https://www.demarches-simplifiees.fr/commencer/udap');
INSERT INTO clause(key,value,udap_id,text) VALUES ('decision','Architecte','ALL','Suite à nos échanges, il ressort qu''il est fortement conseillé d’avoir recours à un architecte ou un maître d’œuvre car votre projet n’est pas réalisable en l’état. Ce professionnel pourra soumettre un nouveau projet soit par l’intermédiaire de la collectivité si une permanence y est assurée par un agent de l’UDAP (voir le contact ci-dessous) soit via : https://www.demarches-simplifiees.fr/commencer/udap');
INSERT INTO clause(key,value,udap_id,text) VALUES ('decision','MH oui','ALL','Suite à nos échanges, il ressort qu’à ce stade il convient de solliciter l''autorisation de la conservation régionale des monuments historiques.');
INSERT INTO clause(key,value,udap_id,text) VALUES ('decision','MH à suivre','ALL','Suite à nos échanges, il ressort que le projet appelle des observations et n’est pas au stade d’avancement nécessaire pour déposer une demande d''autorisation auprès de la conservation régionale des monuments historiques. Il sera nécessaire de le représenter soit par l’intermédiaire de la collectivité si une permanence y est assurée par un agent de l’UDAP (voir le contact ci-dessous) soit via : https://www.demarches-simplifiees.fr/commencer/udap');

INSERT INTO clause(key,value,udap_id,text) VALUES ('contacts-utiles','Pôle architecture','udap-landes','Vous pouvez contacter le pôle architecture de la Direction régionale des affaires culturelles (DRAC) :\nEmanuelle Maillet, emmanuelle.maillet@culture.gouv.fr.');
INSERT INTO clause(key,value,udap_id,text) VALUES ('contacts-utiles','CRMH','udap-landes','Veillez à prendre contact avec la Conservation régionale des monuments historiques (CRMH) :\nSeverine Laborie, Conservatrice - severine.laborie@culture.gouv.fr.');
INSERT INTO clause(key,value,udap_id,text) VALUES ('contacts-utiles','SRA','udap-landes','Veillez à l''éventualité de vestiges archéologiques, vous pouvez contacter le service régional de l’archéologie :\nMathilde Roupsard, Conservatrice - mathilde.roupsard@culture.gouv.fr.');
INSERT INTO clause(key,value,udap_id,text) VALUES ('contacts-utiles','DREAL','udap-landes','Vous pouvez contacter l''inspecteur des Sites de la Direction régionale de l''environnement, de l''aménagement et du logement (DREAL) car votre projet se situe en site protégé :\nLydie Bayle, Inspectrice des Sites - lydie.bayle@developpement-durable.gouv.fr.');
INSERT INTO clause(key,value,udap_id,text) VALUES ('contacts-utiles','DT Dax','udap-landes','Votre projet est susceptible d''être accompagné par le délégué territorial (DDTM) :\nJean-François Mozas, arrondissement Dax, jean-francois.mozas@landes.gouv.fr.');
INSERT INTO clause(key,value,udap_id,text) VALUES ('contacts-utiles','DT MDM','udap-landes','Votre projet est susceptible d''être accompagné par le délégué territorial (DDTM) :\nOlivier Laurin, MDM, olivier.laurin@landes.gouv.fr.');
INSERT INTO clause(key,value,udap_id,text) VALUES ('contacts-utiles','SAR','udap-landes','Votre projet est susceptible d''être accompagné par le service aménagement et risque (DDTM) :\nJulie Lacanal, DDT Landes, julie.lacanal@landes.gouv.fr.');
INSERT INTO clause(key,value,udap_id,text) VALUES ('contacts-utiles','CAUE','udap-landes','Vous pouvez être accompagné par le CAUE qui dispense un conseil architectural gratuit et de qualité :\nCAUE des Landes, contact@caue40.com.');
INSERT INTO clause(key,value,udap_id,text) VALUES ('contacts-utiles','FdP','udap-landes','Vous pouvez contacter la Fondation du patrimoine car votre projet est susceptible de recevoir une aide de leur part :\nJean Mortier, Délégué de la FP, jean.mortier@fondation-patrimoine.org.');
INSERT INTO clause(key,value,udap_id,text) VALUES ('contacts-utiles','PNR','udap-landes','Vous pouvez contacter le parc naturel dans lequel se situe votre projet :');

INSERT INTO clause(key,value,udap_id,text) VALUES ('bonnes-pratiques','DRAC','ALL','Qu’est-ce qu’une DRAC | Direction régionale des affaires culturelles ?\nIl s’agit d’un service déconcentré du ministère de la Culture mettant en œuvre la politique culturelle du ministère en région. (www.culture.gouv.fr/Regions/DRAC-Nouvelle-Aquitaine/Qui-sommes-nous).');
INSERT INTO clause(key,value,udap_id,text) VALUES ('bonnes-pratiques','SPR','ALL','Qu’est-ce qu’un SPR | site patrimonial remarquable ?\nIl s’agit d’un ensemble urbain protégé par un règlement spécifique pour conserver ses qualités urbaines, architecturales et paysagères (www.culture.gouv.fr/Thematiques/Monuments-Sites/Monuments-historiques-sites-patrimoniaux/Les-sites-patrimoniaux-remarquables).');
INSERT INTO clause(key,value,udap_id,text) VALUES ('bonnes-pratiques','Site','ALL','Qu’est-ce qu’un site ?\nIl s’agit d’un espace naturel protégé au regard de sa valeur paysagère. Consultez le site de la DREAL pour en savoir plus. (www.nouvelle-aquitaine.developpement-durable.gouv.fr/sites-r1150.html).');
INSERT INTO clause(key,value,udap_id,text) VALUES ('bonnes-pratiques','Des travaux','ALL','Vous souhaitez entreprendre des travaux ?\nLa démarche pour obtenir une autorisation de travaux varie selon le contexte de votre projet.\nConsultez ce lien pour identifier la démarche adaptée à votre besoin. (www.culture.gouv.fr/Demarches-en-ligne/Par-thematique/Monuments-Sites/Mes-travaux-en-site-protege).');
INSERT INTO clause(key,value,udap_id,text) VALUES ('bonnes-pratiques','Atlas','ALL','Identifier les protections patrimoniales autour de votre bien ?\nUtilisez l’Atlas des patrimoines pour faire apparaître les différents périmètres de protection autour de votre bien. (atlas.patrimoines.culture.fr/).');
INSERT INTO clause(key,value,udap_id,text) VALUES ('bonnes-pratiques','ATHEBA','ALL','Améliorer votre bâti ancien ?\nConsultez les fiches ATHEBA précisant les spécificités techniques du bâti ancien afin de favoriser une amélioration thermique durable (www.rehabilitation-bati-ancien.fr).');
INSERT INTO clause(key,value,udap_id,text) VALUES ('bonnes-pratiques','CREBA','ALL','Réhabiliter un bâti ancien ?\nConsultez le centre de ressources pour la réhabilitation responsable du bâti ancien (CREBA), à destination des professionnels, pour tout projet de réhabilitation ou de restauration (www.rehabilitation-bati-ancien.fr/).');
INSERT INTO clause(key,value,udap_id,text) VALUES ('bonnes-pratiques','FranceRénov','ALL','Être accompagné dans un projet de réhabilitation ?\nConsultez France Rénov, service public de la rénovation de l’habitat, qui oriente les demandeurs tout au long de leur projet de rénovation et assure une mission sociale auprès des ménages modestes (france-renov.gouv.fr).');

ALTER TABLE clause ENABLE ELECTRIC;