CREATE TABLE chip(
   key     text NOT NULL 
  ,value   text NOT NULL
  ,udap_id text
  ,text    text NOT NULL
  , PRIMARY KEY (key, value, udap_id)
);
INSERT INTO chip(key,value,udap_id,text) VALUES ('demandeur','Particulier','ALL','Vous avez rencontré un agent de l’UDAP car votre projet se situe dans un espace protégé pour son patrimoine. Cet agent évalue si votre projet peut s’intégrer à cet espace. Ce jugement ne remplace pas les demandes d’autorisation de travaux. Ci-dessous le compte rendu de l’échange :');
INSERT INTO chip(key,value,udap_id,text) VALUES ('demandeur','Maître d''oeuvre','ALL','Vous avez rencontré un agent de l’UDAP car votre projet se situe dans un espace protégé pour son patrimoine. Le jugement émis ne remplace pas les demandes d’autorisation de travaux. Si la décision est favorable, vous devrez contacter le service instructeur. Notez que le maître d’œuvre sera notre interlocuteur privilégié pour ce projet. Ci-dessous le compte rendu de l’échange :');
INSERT INTO chip(key,value,udap_id,text) VALUES ('demandeur','Collectivité','ALL','Vous avez rencontré un agent de l’UDAP car votre projet se situe dans un espace protégé pour son patrimoine. Cet agent évalue si votre projet peut s’intégrer à cet espace. Le jugement émis ne remplace pas les demandes d’autorisation de travaux. Si la décision est favorable, vous devrez contacter le service instructeur. Ci-dessous le compte rendu de l’échange :');
INSERT INTO chip(key,value,udap_id,text) VALUES ('demandeur','Service de l''État','ALL','Vous avez rencontré un agent de l’UDAP car votre projet se situe dans un espace protégé pour son patrimoine. Dans le cadre de notre relation collégiale, l’UDAP facilitera l’application des règlements en vigueur, de la qualité architecturale et patrimoniale. Nos conseils ne remplacent pas les demandes d’autorisation de travaux. Ci-dessous le compte rendu de l’échange :');
INSERT INTO chip(key,value,udap_id,text) VALUES ('demandeur','Autre','ALL','Vous avez rencontré un agent de l’UDAP car votre projet se situe dans un espace protégé pour son patrimoine. Nos conseils ne remplacent pas les demandes d’autorisation de travaux. Ci-dessous le compte rendu de l’échange :');
INSERT INTO chip(key,value,udap_id,text) VALUES ('etat-actuel','Prog.','ALL','Le projet est en phase de programmation avant conception architecturale.');
INSERT INTO chip(key,value,udap_id,text) VALUES ('etat-actuel','Avant-projet','ALL','Le projet est en phase d’avant-projet.');
INSERT INTO chip(key,value,udap_id,text) VALUES ('etat-actuel','Refus','ALL','Le projet est après le refus d’une précédente autorisation d''urbanisme.');
INSERT INTO chip(key,value,udap_id,text) VALUES ('etat-actuel','Chantier','ALL','Le projet est en chantier avant achèvement des travaux.');
INSERT INTO chip(key,value,udap_id,text) VALUES ('etat-actuel','Conformité','ALL','Le projet est non conforme après achèvement des travaux.');
INSERT INTO chip(key,value,udap_id,text) VALUES ('etat-actuel','Urgence','ALL','Il s’agit d’une situation d’urgence sanitaire.');
INSERT INTO chip(key,value,udap_id,text) VALUES ('type-espace','PSMV','ALL','Situé dans un secteur urbain protégé par le Plan de sauvegarde et de mise en valeur (PSMV), plus haut degré de protection patrimoniale concernant les extérieurs et intérieurs, votre projet devra obligatoirement respecter l’avis ci-dessous.');
INSERT INTO chip(key,value,udap_id,text) VALUES ('type-espace','AVAP','ALL','Situé sur une Aire de mise en valeur de l’architecture et du patrimoine (AVAP) ou une Zone de protection du patrimoine architectural urbain et paysager (ZPPAUP), votre projet devra obligatoirement respecter l’avis ci-dessous.');
INSERT INTO chip(key,value,udap_id,text) VALUES ('type-espace','Abord','ALL','Situé aux abords d''un Monument historique, votre projet doit obligatoirement respecter l’avis ci-dessous.');
INSERT INTO chip(key,value,udap_id,text) VALUES ('type-espace','Périmètre','ALL','Ce projet est proche d''un monument historique, mais sans visibilité entre l''un et l''autre. L''avis ci-dessous est un conseil pour la collectivité délivrant l’autorisation.');
INSERT INTO chip(key,value,udap_id,text) VALUES ('type-espace','Site classé','ALL','Situé sur un site classé, préservant les espaces paysagers, votre projet nécessite un avis ministériel pouvant prendre 8 mois.');
INSERT INTO chip(key,value,udap_id,text) VALUES ('type-espace','Site inscrit','ALL','Ce projet est sur site inscrit, préservant les paysages.');
INSERT INTO chip(key,value,udap_id,text) VALUES ('type-espace','Monument historique classé','ALL','Ce projet concerne un monument historique classé. Nous transmettons donc nos recommandations et votre demande à la Conservation régionale des monuments historiques (CRMH) à qui la décision reviendra.');
INSERT INTO chip(key,value,udap_id,text) VALUES ('type-espace','Monument historique inscrit','ALL','Ce projet concerne un monument historique inscrit. Nous transmettons donc nos recommandations et votre demande à la Conservation régionale des monuments historiques (CRMH) à qui la décision reviendra.');
INSERT INTO chip(key,value,udap_id,text) VALUES ('decision','Sans suite','ALL','Votre demande est classée sans suite.');
INSERT INTO chip(key,value,udap_id,text) VALUES ('decision','Oui','ALL','À l''examen de votre demande, il ressort que ce dossier n''appelle aucune observation particulière. Il peut donc être déposé en mairie en l''état.');
INSERT INTO chip(key,value,udap_id,text) VALUES ('decision','Refus','ALL','À l''examen de votre demande, il ressort que ce dossier n''est pas réalisable car il porte atteinte au cadre patrimonial dans lequel il s''inscrit. S''il venait à faire l''objet du dépôt d''autorisation d''urbanisme, il se verrait refuser. Il convient donc de changer votre projet en tenant compte de la réglementation en vigueur.');
INSERT INTO chip(key,value,udap_id,text) VALUES ('decision','Modif. mini.','ALL','Vous pouvez déposer dès à présent une demande d''autorisation d''urbanisme pouvant donner lieu à des prescriptions ou des observations mineures.');
INSERT INTO chip(key,value,udap_id,text) VALUES ('decision','Dédale','ALL','À l''examen de votre demande, il ressort que ce dossier appelle des observations. Après ces modifications, et avant dépôt de votre demande d’autorisation d’urbanisme, vous pourrez déposer un avant-projet qui donnera lieu à des prescriptions ou des observations.
Déposer un avant-projet : https://www.demarches-simplifiees.fr/commencer/udap');
INSERT INTO chip(key,value,udap_id,text) VALUES ('decision','Architecte','ALL','À l’examen de votre demande, il ressort que ce dossier n’est pas réalisable en l’état. Le recours à un architecte ou un maître d’œuvre s’avère indispensable. Ce professionnel dressera le prochain projet qui nous sera proposé sous forme d’une consultation préalable.
Lien pour déposer une consultation préalable : https://www.demarches-simplifiees.fr/commencer/udap');
INSERT INTO chip(key,value,udap_id,text) VALUES ('decision','Rdv','ALL','À l''examen de votre demande, il ressort que ce dossier appelle des observations importantes. 
Un rendez-vous avec l''agent de l’UDAP chargé de votre dossier s’avère nécessaire. Privilégiez nos permanences (si votre intercommunalité l''organise) ou à défaut un RDV dans nos bureaux (voir contact en bas du courrier).');
INSERT INTO chip(key,value,udap_id,text) VALUES ('decision','A suivre','ALL','Votre projet n''est pas encore au stade d’avancement nécessaire pour obtenir un avis de notre part. Il sera nécessaire de le représenter lorsqu''il aura suffisamment avancé. Privilégiez nos permanences (si votre intercommunalité l''organise) ou à défaut un RDV dans nos bureaux (voir contact en bas du courrier).');
INSERT INTO chip(key,value,udap_id,text) VALUES ('contacts-utiles','DRAC','udap-landes','Votre projet relève de la DRAC, contactez 
Emmanuelle Maillet, Conseillère Architecture - emmanuelle.maillet@culture.gouv.fr.');
INSERT INTO chip(key,value,udap_id,text) VALUES ('contacts-utiles','CRMH','udap-landes','Il est important de contacter la conservation régionale des monuments historiques (CRMH) de Poitiers. Contactez
Severine Laborie, Conservatrice - severine.laborie@culture.gouv.fr.');
INSERT INTO chip(key,value,udap_id,text) VALUES ('contacts-utiles','SRA','udap-landes','Veillez à l''éventualité de vestiges archéologiques. Contactez
Mathilde Roupsard, Conservatrice - mathilde.roupsard@culture.gouv.fr.');
INSERT INTO chip(key,value,udap_id,text) VALUES ('contacts-utiles','DREAL','udap-landes','Votre projet se situe en site. Contactez
Lydie Bayle, Inspectrice des Sites - lydie.bayle@developpement-durable.gouv.fr.');
INSERT INTO chip(key,value,udap_id,text) VALUES ('contacts-utiles','Mozas','udap-landes','Votre projet est susceptible d''être accompagné par la mission cohésion des territoires. Veuillez contacter Jean-François Mozas, Délégué Territorial de l’arrondissement de Dax - jean-francois.mozas@landes.gouv.fr.');
INSERT INTO chip(key,value,udap_id,text) VALUES ('contacts-utiles','Laurin','udap-landes','Votre projet est susceptible d''être accompagné par la mission cohésion des territoires. Veuillez contacter Olivier Laurin, Délégué Territorial de arrondissement  MDM - olivier.laurin@landes.gouv.fr.');
INSERT INTO chip(key,value,udap_id,text) VALUES ('contacts-utiles','Lacanal','udap-landes','Votre projet est susceptible d''être accompagné par la Direction départementale des territoires et de la mer. Veuillez contacter Julie Lacanal, Cheffe de service aménagement et risques - julie.lacanal@landes.gouv.fr.');
INSERT INTO chip(key,value,udap_id,text) VALUES ('contacts-utiles','CAUE','udap-landes','Le CAUE des Landes dispense un conseil architectural gratuit et de qualité qui bonifiera votre projet. Veuillez contacter CAUE des Landes, Conseil - contact@caue40.com.');
INSERT INTO chip(key,value,udap_id,text) VALUES ('contacts-utiles','FdP','udap-landes','Votre projet est susceptible de recevoir une aide de la part de la Fondation du patrimoine. Veuillez contacter Jean Mortier, Délégué de la FP - jean.mortier@fondation-patrimoine.org.');
INSERT INTO chip(key,value,udap_id,text) VALUES ('contacts-utiles','s.o.','udap-landes','Sans objet.');
INSERT INTO chip(key,value,udap_id,text) VALUES ('contacts-utiles','DRAC','udap-deux-sèvres','Votre projet concerne plusieurs champs qui relèvent de la DRAC. Veuillez contacter Johanne Peyras, conseillère Démocratisation et action territoriale - johanne.peyras@culture.gouv.fr - 05 49 36 30 50 (DRAC Nouvelle-Aquitaine - site de Poitiers, 102 Grand''Rue - BP 553, 86020 Poitiers Cedex).');
INSERT INTO chip(key,value,udap_id,text) VALUES ('contacts-utiles','CRMH','udap-deux-sèvres','Il est important que vous preniez contact avec la conservation régionale des monuments historiques (CRMH) du site de Poitiers. Veuillez contacter Pauline Lucas, conservatrice des monuments historiques de la Charente et des Deux-Sèvres - pauline.lucas@culture.gouv.fr - 05 49 36 30 10 (DRAC Nouvelle-Aquitaine - site de Poitiers, 102 Grand''Rue - BP 553, 86020 Poitiers Cedex).');
INSERT INTO chip(key,value,udap_id,text) VALUES ('contacts-utiles','SRA','udap-deux-sèvres','Une attention particulière doit être portée à l''éventualité de vestiges archéologiques sur le site. Veuillez contacter Jérôme Primault, conservateur du patrimoine
Service Régional de l’Archéologie - jerome.primault@culture.gouv.fr - 05 49 36 30 64 (DRAC Nouvelle-Aquitaine - site de Poitiers, 102 Grand''Rue - BP 553, 86020 Poitiers Cedex).');
INSERT INTO chip(key,value,udap_id,text) VALUES ('contacts-utiles','Provost','udap-deux-sèvres','Votre projet se situe en site. Veuillez contacter Sylvain Provost, inspecteur des sites - sylvain.provost@developpement-durable.gouv.fr - 07 64 67 37 19 (DREAL Nouvelle-Aquitaine, 15 rue Arthur-Ranc, 86020 Poitiers Cedex).');
INSERT INTO chip(key,value,udap_id,text) VALUES ('contacts-utiles','Nau','udap-deux-sèvres','Votre projet est suceptible d''être accompagné par la mission cohésion des territoires. Veuillez contacter Isabelle Nau, référente territoriale - isabelle.nau@deux-sevres.gouv.fr - 05 49 06 88 88 (Direction départementale des territoires, 39 avenue de Paris, 79022 Niort Cedex 9).');
INSERT INTO chip(key,value,udap_id,text) VALUES ('contacts-utiles','Gouet','udap-deux-sèvres','Votre projet est suceptible d''être accompagné par la mission cohésion des territoires. Veuillez contacter Oliver Gouet, référent territorial - olivier.gouet@deux-sevres.gouv.fr - 05 49 06 88 88 (Direction départementale des territoires, 39 avenue de Paris, 79022 Niort Cedex 9).');
INSERT INTO chip(key,value,udap_id,text) VALUES ('contacts-utiles','Cornut','udap-deux-sèvres','Votre projet est suceptible d''être accompagné par la mission cohésion des territoires. Veuillez contacter Thierry Cornus, référent territorial - thierry.cornusdeux-sevres.gouv.fr - 05 49 06 88 88 (Direction départementale des territoires, 39 avenue de Paris, 79022 Niort Cedex 9).');
INSERT INTO chip(key,value,udap_id,text) VALUES ('contacts-utiles','CAUE','udap-deux-sèvres','Le CAUE des Deux-Sèvres dispense un conseil architectural gratuit et de qualité qui bonifiera votre projet. Veuillez contacter le conseil d’architecture, d’urbanisme et de l’environnement (CAUE) - contact@caue79.fr - 05 49 28 06 28 (, Mail Lucie Aubrac, cs 58880, 79028 Niort cedex).');
INSERT INTO chip(key,value,udap_id,text) VALUES ('contacts-utiles','Fdp','udap-deux-sèvres','Votre projet est susceptible de recevoir une aide de la part de la Fondation du patrimoine. Veuillez contacter Aurélie Liège, chargée de mission de la Délégation Poitou-Charentes - aurelie.liege@fondation-patrimoine.org - 06 59 54 62 15 / 05 49 41 45 54 (Fondation du patrimoine, 1 bis rue Lebascles, 8600 Poitiers).');
INSERT INTO chip(key,value,udap_id,text) VALUES ('contacts-utiles','PNRMP','udap-deux-sèvres','Votre projet se situe dans le périmètre du Parc naturel et peut bénéficier du conseil de son architecte. Veuillez contacter Gaële Calvez, architecte conseil - g.calvez@parc-marais-poitevin.fr - 05 49 35 15 20 (Parc naturel régional du Marais poitevin, 2 Rue de l''Église, 79510 Coulon).');
INSERT INTO chip(key,value,udap_id,text) VALUES ('contacts-utiles','s.o.','udap-deux-sèvres','Sans objet.');
INSERT INTO chip(key,value,udap_id,text) VALUES ('bonnes-pratiques','DRAC','ALL','Qu’est-ce qu’une DRAC | Direction régionale des affaires culturelles ? 
Il s’agit d’un service déconcentré du ministère de la Culture mettant en œuvre la politique culturelle du ministère en région. (www.culture.gouv.fr/Regions/DRAC-Nouvelle-Aquitaine/Qui-sommes-nous).');
INSERT INTO chip(key,value,udap_id,text) VALUES ('bonnes-pratiques','SPR','ALL','Qu’est-ce qu’un SPR | site patrimonial remarquable ? 
Il s’agit d’un ensemble urbain protégé par un règlement patrimonial spécifique pour mettre en valeur les espaces bâtis et non bâtis. (www.culture.gouv.fr/Thematiques/Monuments-Sites/Monuments-historiques-sites-patrimoniaux/Les-sites-patrimoniaux-remarquables).');
INSERT INTO chip(key,value,udap_id,text) VALUES ('bonnes-pratiques','Site','ALL','Qu’est-ce qu’un site ? 
Il s’agit d’une politique visant à préserver des lieux au regard de leur qualité paysagère. Consultez le site de la DREAL pour en savoir plus. (www.nouvelle-aquitaine.developpement-durable.gouv.fr/sites-r1150.html).');
INSERT INTO chip(key,value,udap_id,text) VALUES ('bonnes-pratiques','Des travaux','ALL','Vous souhaitez entreprendre des travaux ? 
La démarche pour obtenir une autorisation de travaux varie selon le contexte de votre projet. 
Consultez ce lien pour identifier la démarche adaptée à votre besoin. (www.culture.gouv.fr/Demarches-en-ligne/Par-thematique/Monuments-Sites/Mes-travaux-en-site-protege).');
INSERT INTO chip(key,value,udap_id,text) VALUES ('bonnes-pratiques','Atlas','ALL','Identifier les protections patrimoniales autour de votre bien ?
Utilisez l’Atlas du patrimoine pour faire apparaître les différents périmètres de protection autour de votre bien. (atlas.patrimoines.culture.fr/).');
INSERT INTO chip(key,value,udap_id,text) VALUES ('bonnes-pratiques','ATHEBA','ALL','Améliorer votre bâti ancien ? 
Consultez les fiches ATHEBA précisant les spécificités techniques du bâti ancien afin de favoriser une amélioration thermique durable (www.rehabilitation-bati-ancien.fr).');
INSERT INTO chip(key,value,udap_id,text) VALUES ('bonnes-pratiques','CREBA','ALL','Réhabiliter un bâti ancien ? 
Consultez le centre de ressources pour la réhabilitation responsable du bâti ancien (CREBA), à destination des professionnels, pour tout projet de réhabilitation ou de restauration (www.rehabilitation-bati-ancien.fr/).');
INSERT INTO chip(key,value,udap_id,text) VALUES ('bonnes-pratiques','FranceRénov','ALL','Être accompagné dans un projet de réhabilitation ? 
Consultez France Rénov, service public de la rénovation de l’habitat, oriente les demandeurs tout au long de leur projet de rénovation et assure une mission sociale auprès des ménages modestes (france-renov.gouv.fr).');

ALTER TABLE chip ENABLE ELECTRIC;