import {
  pgTable,
  integer,
  text,
  timestamp,
  boolean,
  foreignKey,
  unique,
  varchar,
  index,
  primaryKey,
} from "drizzle-orm/pg-core";

export const user = pgTable(
  "user",
  {
    id: text().primaryKey().notNull(),
    name: text().notNull(),
    serviceId: text("service_id").notNull(),
    email: varchar({ length: 255 }).notNull(),
  },
  (table) => [
    foreignKey({
      columns: [table.serviceId],
      foreignColumns: [service.id],
      name: "user_service_id_fkey",
    }).onDelete("set null"),
    unique("user_email_key").on(table.email),
  ],
);

export const internalUser = pgTable(
  "internal_user",
  {
    id: text().primaryKey().notNull(),
    email: text().notNull(),
    role: text().notNull(),
    temporaryLink: text(),
    temporaryLinkExpiresAt: text(),
    userId: text().notNull(),
  },
  (table) => [
    foreignKey({
      columns: [table.userId],
      foreignColumns: [user.id],
      name: "internal_user_userId_fkey",
    }).onDelete("cascade"),
  ],
);

export const delegation = pgTable(
  "delegation",
  {
    id: text().primaryKey().notNull(),
    createdBy: text().notNull(),
    delegatedTo: text().notNull(),
  },
  (table) => [
    foreignKey({
      columns: [table.createdBy],
      foreignColumns: [user.id],
      name: "delegation_createdBy_fkey",
    }).onDelete("cascade"),
    foreignKey({
      columns: [table.delegatedTo],
      foreignColumns: [user.id],
      name: "delegation_delegatedTo_fkey",
    }).onDelete("cascade"),
  ],
);

export const serviceInstructeurs = pgTable("service_instructeurs", {
  id: text().primaryKey().notNull(),
  fullName: text("full_name").notNull(),
  shortName: text("short_name").notNull(),
  email: text(),
  tel: text(),
  serviceId: text("service_id"),
});

export const whitelist = pgTable("whitelist", {
  email: text().primaryKey().notNull(),
});

export const service = pgTable("service", {
  id: text().primaryKey().notNull(),
  visible: boolean(),
  name: text(),
  email: text(),
  marianneText: text("marianne_text"),
  dracText: text("drac_text"),
  serviceText: text("service_text"),
  deptNumbers: text("dept_numbers"), // comma separated

  // TODO: make sure those are useful
  department: text().notNull(),
  completeCoords: text(),
  address: text(),
  zipCode: text(),
  city: text(),
  phone: text(),
});

export const clauseV2 = pgTable("clause_v2", {
  id: text().primaryKey().notNull(),
  key: text().notNull(),
  value: text().notNull(),
  position: integer(),
  serviceId: text("service_id"),
  text: text().notNull(),
});

export const report = pgTable(
  "report",
  {
    id: text().primaryKey().notNull(),
    title: text(),
    projectDescription: text(),
    redactedBy: text(),
    meetDate: timestamp({ mode: "string" }),
    applicantName: text(),
    applicantAddress: text(),
    projectCadastralRef: text(),
    projectSpaceType: text(),
    decision: text(),
    precisions: text(),
    contacts: text(),
    furtherInformation: text(),
    createdBy: text().notNull(),
    createdAt: timestamp({ mode: "string" }).notNull(),
    serviceInstructeur: text(),
    pdf: text(),
    attachmentId: text("attachment_id"),
    disabled: boolean(),
    serviceId: text("service_id"),
    redactedById: text(),
    applicantEmail: text(),
    city: text(),
    zipCode: text(),
  },
  (table) => [
    foreignKey({
      columns: [table.createdBy],
      foreignColumns: [user.id],
      name: "report_createdBy_fkey",
    }).onDelete("set null"),
  ],
);

export const reportAttachment = pgTable("report_attachment", {
  id: text().primaryKey().notNull(),
  isDeprecated: boolean("is_deprecated"),
  attachmentId: text("attachment_id").notNull(),
  reportId: text("report_id").notNull(),
  createdAt: timestamp("created_at", { mode: "string" }),
  service_id: text("service_id"),
});

export const stateReportAttachment = pgTable("state_report_attachment", {
  id: text().primaryKey().notNull(),
  isDeprecated: boolean("is_deprecated"),
  attachmentId: text("attachment_id").notNull(),
  stateReportId: text("state_report_id").notNull(),
  createdAt: timestamp("created_at", { mode: "string" }),
  label: text(),
  service_id: text("service_id"),
});

export const pdfSnapshot = pgTable("pdf_snapshot", {
  id: text().primaryKey().notNull(),
  reportId: text("report_id"),
  html: text(),
  report: text(),
  userId: text("user_id"),
});

export const pictureLines = pgTable("picture_lines", {
  id: text().primaryKey().notNull(),
  attachmentId: text("attachmentId").notNull(),
  lines: text().notNull(),
  createdAt: timestamp({ mode: "string" }),
  table: text().notNull(),
  serviceId: text("service_id"),
});

export const pictures = pgTable(
  "pictures",
  {
    id: text().primaryKey().notNull(),
    reportId: text(),
    url: text(),
    createdAt: timestamp({ mode: "string" }),
    finalUrl: text(),
  },
  (table) => [
    foreignKey({
      columns: [table.reportId],
      foreignColumns: [report.id],
      name: "pictures_reportId_fkey",
    }).onDelete("cascade"),
  ],
);

export const transactions = pgTable("transactions", {
  id: text().primaryKey().notNull(),
  opId: integer("op_id").notNull(),
  txId: integer("tx_id"),
  entityId: text("entity_id").notNull(),
  type: text().notNull(),
  op: text().notNull(),
  data: text(),
  userId: text("user_id").notNull(),
  createdAt: timestamp("created_at", { mode: "string" }),
  error: text(),
});

export const sentEmail = pgTable(
  "sent_email",
  {
    id: text().primaryKey().notNull(),
    reportId: text("report_id"),
    sentTo: text("sent_to").notNull(),
    sentAt: timestamp("sent_at", { mode: "string" }).notNull(),
    serviceId: text("service_id").notNull(),
  },
  (table) => [
    foreignKey({
      columns: [table.reportId],
      foreignColumns: [report.id],
      name: "sent_email_report_id_fkey",
    }),
  ],
);

export const stateReportSentEmail = pgTable(
  "state_report_sent_email",
  {
    id: text().primaryKey().notNull(),
    stateReportId: text("state_report_id"),
    sentTo: text("sent_to").notNull(),
    sentAt: timestamp("sent_at", { mode: "string" }).notNull(),
    serviceId: text("service_id").notNull(),
  },
  (table) => [
    foreignKey({
      columns: [table.stateReportId],
      foreignColumns: [stateReport.id],
      name: "state_report_sent_email_state_report_id_fkey",
    }),
  ],
);

export const suggestedEmail = pgTable(
  "suggested_email",
  {
    id: text().primaryKey().notNull(),
    email: text().notNull(),
    serviceId: text("service_id").notNull(),
  },
  (table) => [unique("suggested_email_email_key").on(table.email)],
);

export const userSettings = pgTable("user_settings", {
  id: text().primaryKey().notNull(),
  userId: text("user_id"),
  defaultEmails: text("default_emails"),
  serviceId: text("service_id"),
});

export const merimee = pgTable(
  "merimee",
  {
    rowid: integer(),
    acmh: text("ACMH"),
    actu: text("ACTU"),
    acurl: text("ACURL"),
    adrs: text("ADRS"),
    affe: text("AFFE"),
    aire: text("AIRE"),
    appl: text("APPL"),
    apro: text("APRO"),
    archeo: text("ARCHEO"),
    autp: text("AUTP"),
    autr: text("AUTR"),
    base: text("BASE"),
    cada: text("CADA"),
    cant: text("CANT"),
    coll: text("COLL"),
    com: text("COM"),
    contact: text("CONTACT"),
    contientImage: text("CONTIENT_IMAGE"),
    coor: text("COOR"),
    coorm: text("COORM"),
    copy: text("COPY"),
    couv: text("COUV"),
    date: text("DATE"),
    dbor: text("DBOR"),
    deno: text("DENO"),
    denq: text("DENQ"),
    depl: text("DEPL"),
    desc: text("DESC"),
    dims: text("DIMS"),
    dlab: text("DLAB"),
    "dmaj(date)": text("DMAJ(DATE)"),
    "dmis(date)": text("DMIS(DATE)"),
    domn: text("DOMN"),
    dosadrs: text("DOSADRS"),
    doss: text("DOSS"),
    dosurl: text("DOSURL"),
    dosurlpdf: text("DOSURLPDF"),
    dpro: text("DPRO"),
    dpt: text("DPT"),
    dptLettre: text("DPT_LETTRE"),
    edif: text("EDIF"),
    elev: text("ELEV"),
    ener: text("ENER"),
    esca: text("ESCA"),
    etag: text("ETAG"),
    etat: text("ETAT"),
    etud: text("ETUD"),
    genr: text("GENR"),
    hist: text("HIST"),
    hydr: text("HYDR"),
    idagr: text("IDAGR"),
    image: text("IMAGE"),
    img: text("IMG"),
    impl: text("IMPL"),
    insee: text("INSEE"),
    inte: text("INTE"),
    jatt: text("JATT"),
    jdat: text("JDAT"),
    liens: text("LIENS"),
    lieu: text("LIEU"),
    linha: text("LINHA"),
    lmdp: text("LMDP"),
    loca: text("LOCA"),
    lreg: text("LREG"),
    mfich: text("MFICH"),
    mhpp: text("MHPP"),
    micr: text("MICR"),
    mosa: text("MOSA"),
    murs: text("MURS"),
    nbor: text("NBOR"),
    noms: text("NOMS"),
    obs: text("OBS"),
    paff: text("PAFF"),
    parn: text("PARN"),
    part: text("PART"),
    pden: text("PDEN"),
    pers: text("PERS"),
    pint: text("PINT"),
    plan: text("PLAN"),
    ploc: text("PLOC"),
    popArreteProtection: text("POP_ARRETE_PROTECTION"),
    popContientGeolocalisation: text("POP_CONTIENT_GEOLOCALISATION"),
    popCoordinatesPoint: text("POP_COORDINATES_POINT"),
    popCoordinatesPolygon: text("POP_COORDINATES_POLYGON"),
    popCoordonnees: text("POP_COORDONNEES"),
    popDate: text("POP_DATE"),
    popDossierProtection: text("POP_DOSSIER_PROTECTION"),
    popDossierVert: text("POP_DOSSIER_VERT"),
    popFlags: text("POP_FLAGS"),
    popHasLocation: text("POP_HAS_LOCATION"),
    popImport: text("POP_IMPORT"),
    ppro: text("PPRO"),
    prep: text("PREP"),
    producteur: text("PRODUCTEUR"),
    prot: text("PROT"),
    psta: text("PSTA"),
    ref: text("REF").primaryKey().notNull(),
    refe: text("REFE"),
    refim: text("REFIM"),
    refjoc: text("REFJOC"),
    refm: text("REFM"),
    refmus: text("REFMUS"),
    refo: text("REFO"),
    refp: text("REFP"),
    reg: text("REG"),
    rema: text("REMA"),
    remp: text("REMP"),
    renv: text("RENV"),
    repr: text("REPR"),
    rfpa: text("RFPA"),
    scld: text("SCLD"),
    scle: text("SCLE"),
    sclx: text("SCLX"),
    site: text("SITE"),
    stat: text("STAT"),
    tech: text("TECH"),
    them: text("THEM"),
    tico: text("TICO"),
    toit: text("TOIT"),
    tout: text("TOUT"),
    typo: text("TYPO"),
    vert: text("VERT"),
    video: text("VIDEO"),
    visi: text("VISI"),
    voca: text("VOCA"),
    vout: text("VOUT"),
    wadrs: text("WADRS"),
    wcom: text("WCOM"),
    web: text("WEB"),
    wrenv: text("WRENV"),
    zone: text("ZONE"),
  },
  (table) => [
    index("merimee_dpt").using("btree", table.dpt.asc().nullsLast().op("text_ops")),
    index("merimee_insee").using("btree", table.insee.asc().nullsLast().op("text_ops")),
    index("merimee_producteur").using("btree", table.producteur.asc().nullsLast().op("text_ops")),
  ],
);

export const popObjets = pgTable("pop_objets", {
  id: text().notNull(),
  reference: text().primaryKey().notNull(),
  contexte_d_acquisition: text("contexte_d_acquisition"),
  adresse_forme_index: text("adresse_forme_index"),
  auteur_du_projet: text("auteur_du_projet"),
  appellation_d_usage: text("appellation_d_usage"),
  personne_morale_creatrice_de_l_objet: text("personne_morale_creatrice_de_l_objet"),
  auteur_de_l_oeuvre_ou_createur_de_l_objet: text("auteur_de_l_oeuvre_ou_createur_de_l_objet"),
  references_de_publications: text("references_de_publications"),
  categorie_technique: text("categorie_technique"),
  commune_forme_index: text("commune_forme_index"),
  copyright: text("copyright"),
  annee_de_creation: text("annee_de_creation"),
  denomination: text("denomination"),
  date_du_recolement: text("date_du_recolement"),
  lieu_de_deplacement_de_l_objet: text("lieu_de_deplacement_de_l_objet"),
  description: text("description"),
  dimensions: text("dimensions"),
  date_de_la_derniere_mise_a_jour: text("date_de_la_derniere_mise_a_jour"),
  date_de_creation_de_la_notice: text("date_de_creation_de_la_notice"),
  domaine: text(),
  date_et_typologie_de_la_protection: text("date_et_typologie_de_la_protection"),
  departement_format_numerique: text("departement_format_numerique"),
  region: text("region"),
  departement_en_lettres: text("departement_en_lettres"),
  nom_de_l_edifice: text("nom_de_l_edifice"),
  emplacement_de_l_oeuvre_dans_l_edifice: text("emplacement_de_l_oeuvre_dans_l_edifice"),
  etat: text("etat"),
  cadre_de_l_etude: text("cadre_de_l_etude"),
  lieu_de_creation: text("lieu_de_creation"),
  references_d_expositions: text("references_d_expositions"),
  historique: text("historique"),
  identifiant_agregee: text("identifiant_agregee"),
  inscription: text("inscription"),
  cog_insee: text("cog_insee"),
  justification_de_la_datation: text("justification_de_la_datation"),
  lien_vers_la_base_arcade: text("lien_vers_la_base_arcade"),
  liens_externes: text("liens_externes"),
  lieudit: text("lieudit"),
  lien_vers_la_base_inha: text("lien_vers_la_base_inha"),
  lien_vers_la_base_archiv_mh: text("lien_vers_la_base_archiv_mh"),
  statut_juridique_de_l_objet: text("statut_juridique_de_l_objet"),
  materiaux: text("materiaux"),
  numero_artificiel_de_differenciation_de_l_objet: text("numero_artificiel_de_differenciation_de_l_objet"),
  numero_d_inventaire_affecte_a_l_objet: text("numero_d_inventaire_affecte_a_l_objet"),
  nom_du_redacteur: text("nom_du_redacteur"),
  numero_de_l_arrete_de_protection: text("numero_de_l_arrete_de_protection"),
  observations: text("observations"),
  lieu_de_provenance: text("lieu_de_provenance"),
  intitule_de_l_ensemble: text("intitule_de_l_ensemble"),
  partie_constituante_non_etudiee: text("partie_constituante_non_etudiee"),
  partie_constituante: text("partie_constituante"),
  precision_sur_la_denomination: text("precision_sur_la_denomination"),
  precision_sur_les_dimensions: text("precision_sur_les_dimensions"),
  personnes_liees_a_l_objet: text("personnes_liees_a_l_objet"),
  precision_sur_l_etat: text("precision_sur_l_etat"),
  precision_sur_l_inscription: text("precision_sur_l_inscription"),
  precision_sur_la_localisation: text("precision_sur_la_localisation"),
  precision_sur_la_protection: text("precision_sur_la_protection"),
  precision_sur_la_representation: text("precision_sur_la_representation"),
  typologie_de_la_protection: text("typologie_de_la_protection"),
  reference_a_une_notice_merimee_mh: text("reference_a_une_notice_merimee_mh"),
  reference_a_un_ensemble: text("reference_a_un_ensemble"),
  lien_vers_la_base_joconde: text("lien_vers_la_base_joconde"),
  lien_vers_la_base_museofile: text("lien_vers_la_base_museofile"),
  reference_a_une_partie_constituante: text("reference_a_une_partie_constituante"),
  renvoi_vers_une_notice_palissy_mh_ou_merimee_mh: text("renvoi_vers_une_notice_palissy_mh_ou_merimee_mh"),
  indexation_iconographique_normalisee: text("indexation_iconographique_normalisee"),
  siecle_de_creation: text("siecle_de_creation"),
  format_abrege_du_siecle_de_creation: text("format_abrege_du_siecle_de_creation"),
  sources_d_archives_et_bases_de_donnees_de_reference: text("sources_d_archives_et_bases_de_donnees_de_reference"),
  etape_de_creation: text("etape_de_creation"),
  statut_juridique_du_proprietaire: text("statut_juridique_du_proprietaire"),
  structure_et_typologie: text("structure_et_typologie"),
  theme_de_l_etude: text("theme_de_l_etude"),
  titre_editorial: text("titre_editorial"),
  titre_iconographique: text("titre_iconographique"),
  informations_relatives_aux_vols: text("informations_relatives_aux_vols"),
  adresse_forme_editoriale: text("adresse_forme_editoriale"),
  commune_forme_editoriale: text("commune_forme_editoriale"),
  typologie_du_dossier: text("typologie_du_dossier"),
  code_insee_commune_actuelle: text("code_insee_commune_actuelle"),
  edifice_actuel: text("edifice_actuel"),
});

export const popImmeubles = pgTable("pop_immeubles", {
  reference: text().primaryKey().notNull(),
  destinationActuelleDeLEdifice: text("destination_actuelle_de_l_edifice"),
  adresseFormeIndex: text("adresse_forme_index"),
  etablissementAffectataireDeLEdifice: text("etablissement_affectataire_de_l_edifice"),
  autreAppellationDeLEdifice: text("autre_appellation_de_l_edifice"),
  natureDeLaProtection: text("nature_de_la_protection"),
  auteurDeLEdifice: text("auteur_de_l_edifice"),
  cadastre: text(),
  communeFormeIndex: text("commune_forme_index"),
  copyright: text(),
  typeDeCouverture: text("type_de_couverture"),
  datationDeLEdifice: text("datation_de_l_edifice"),
  denominationDeLEdifice: text("denomination_de_l_edifice"),
  lieuDeConservationDUnElementArchitecturalDeplace: text("lieu_de_conservation_d_un_element_architectural_deplace"),
  descriptionDeLEdifice: text("description_de_l_edifice"),
  dimensionsNormaliseesDesEdiculesUniquement: text("dimensions_normalisees_des_edicules_uniquement"),
  dateDeLabel: text("date_de_label"),
  dateDeLaDerniereMiseAJour: text("date_de_la_derniere_mise_a_jour"),
  dateDeCreationDeLaNotice: text("date_de_creation_de_la_notice"),
  domaine: text(),
  typologieDuDossier: text("typologie_du_dossier"),
  dateEtTypologieDeLaProtection: text("date_et_typologie_de_la_protection"),
  departementFormatNumerique: text("departement_format_numerique"),
  partieDElevationExterieure: text("partie_d_elevation_exterieure"),
  sourceDeLEnergieUtiliseeParLEdifice: text("source_de_l_energie_utilisee_par_l_edifice"),
  emplacementFormeEtStructureDeLEscalier: text("emplacement__forme_et_structure_de_l_escalier"),
  descriptionDeLElevationInterieure: text("description_de_l_elevation_interieure"),
  etatDeConservation: text("etat_de_conservation"),
  cadreDeLEtude: text("cadre_de_l_etude"),
  genreDuDestinataire: text("genre_du_destinataire"),
  historique: text(),
  nomDuCoursDEauTraversantOuBordantLEdifice: text("nom_du_cours_d_eau_traversant_ou_bordant_l_edifice"),
  identifiantAgregee: text("identifiant_agregee"),
  cogInseeLorsDeLaProtection: text("cog_insee_lors_de_la_protection"),
  justificationAttribution: text("justification_attribution"),
  justificationDeLaDatation: text("justification_de_la_datation"),
  liensExternes: text("liens_externes"),
  lieudit: text(),
  lienVersLaBaseArchivMh: text("lien_vers_la_base_archiv_mh"),
  materiauxDuGrosOeuvre: text("materiaux_du_gros_oeuvre"),
  observations: text(),
  precisionAffectataire: text("precision_affectataire"),
  partieConstituanteNonEtudiee: text("partie_constituante_non_etudiee"),
  partieConstituante: text("partie_constituante"),
  precisionSurLaDenomination: text("precision_sur_la_denomination"),
  personnesLieesALEdifice: text("personnes_liees_a_l_edifice"),
  typologieDePlan: text("typologie_de_plan"),
  precisionDeLaLocalisation: text("precision_de_la_localisation"),
  precisionDeLaProtection: text("precision_de_la_protection"),
  descriptionDeLIconographie: text("description_de_l_iconographie"),
  typologieDeLaProtection: text("typologie_de_la_protection"),
  precisionSurLeStatutDeLEdifice: text("precision_sur_le_statut_de_l_edifice"),
  referenceAUnEnsemble: text("reference_a_un_ensemble"),
  lienVersLaBaseJoconde: text("lien_vers_la_base_joconde"),
  lienVersLaBasePalissy: text("lien_vers_la_base_palissy"),
  referencesDesPartiesConstituantesEtudiees: text("references_des_parties_constituantes_etudiees"),
  région: text("région"),
  département: text("département"),
  elementsRemarquablesDansLEdifice: text("elements_remarquables_dans_l_edifice"),
  remploi: text(),
  renvoiVersUneNoticeDeLaBaseMerimeeOuPalissy: text("renvoi_vers_une_notice_de_la_base_merimee_ou_palissy"),
  indexationIconographiqueNormalisee: text("indexation_iconographique_normalisee"),
  siecleDeCampagneSecondaireDeConstruction: text("siecle_de_campagne_secondaire_de_construction"),
  siecleDeLaCampagnePrincipaleDeConstruction: text("siecle_de_la_campagne_principale_de_construction"),
  formatAbregeDuSiecleDeConstruction: text("format_abrege_du_siecle_de_construction"),
  typologieDeLaZoneDeProtection: text("typologie_de_la_zone_de_protection"),
  statutJuridiqueDeLEdifice: text("statut_juridique_de_l_edifice"),
  techniqueDuDecorPorteDeLEdifice: text("technique_du_decor_porte_de_l_edifice"),
  titreEditorialDeLaNotice: text("titre_editorial_de_la_notice"),
  materiauxDeLaCouverture: text("materiaux_de_la_couverture"),
  couvertsOuDecouvertsDuJardinDeLEdifice: text("couverts_ou_decouverts_du_jardin_de_l_edifice"),
  vocablePourLesEdificesCultuels: text("vocable___pour_les_edifices_cultuels"),
  typologieDuCouvrement: text("typologie_du_couvrement"),
  adresseFormeEditoriale: text("adresse_forme_editoriale"),
  communeFormeEditoriale: text("commune_forme_editoriale"),
  coordonneesAuFormatWgs84: text("coordonnees_au_format_wgs84"),
  id: text(),
});

export const stateReport = pgTable(
  "state_report",
  {
    id: text().primaryKey().notNull(),
    // monument
    natureEdifice: text("nature_edifice"),
    redactedByName: text("redacted_by_name"),
    redactedById: text("redacted_by_id"),
    referencePop: text("reference_pop"),
    adresse: text(),
    commune: text(),
    codePostal: text("code_postal"),
    communeHistorique: text("commune_historique"),
    referenceCadastrale: text("reference_cadastrale"),
    periodeConstruction: text("periode_construction"),
    natureProtection: text("nature_protection"),
    partiesProtegees: text("parties_protegees"),
    description: text(),
    observations: text(),
    titre_edifice: text("titre_edifice"),
    // contexte de la visite
    natureVisite: text("nature_visite"),
    visite_partielle_details: text("visite_partielle_details"),
    bilanQuinquennal: text("bilan_quinquennal"),
    dateVisite: timestamp("date_visite", { mode: "string" }),
    redactedBy: text("redacted_by"),
    personnes_presentes: text("personnes_presentes"),

    proprietaire: text(),
    proprietaireEmail: text("proprietaire_email"),
    proprietaireRepresentant: text("proprietaire_representant"),
    proprietaireRepresentantEmail: text("proprietaire_representant_email"),

    // constat général
    etatGeneral: text("etat_general"),
    proportionDansCetEtat: text("proportion_dans_cet_etat"),
    etatCommentaires: text("etat_commentaires"),
    planSituation: text("plan_situation"),
    planEdifice: text("plan_edifice"),
    vueGenerale: text("vue_generale"),
    preconisations: text(),
    preconisations_commentaires: text("preconisations_commentaires"),

    attachmentId: text("attachment_id"),

    serviceId: text("service_id").notNull(),
    createdBy: text("created_by").notNull(),
    createdAt: timestamp("created_at", { mode: "string" }).notNull(),
    disabled: boolean(),
  },
  (table) => [
    foreignKey({
      columns: [table.createdBy],
      foreignColumns: [user.id],
      name: "state_report_created_by_fkey",
    }),
  ],
);

export const visitedSection = pgTable(
  "visited_section",
  {
    id: text().primaryKey().notNull(),
    stateReportId: text("state_report_id").notNull(),
    section: text(),
    etatGeneral: text("etat_general"),
    proportionDansCetEtat: text("proportion_dans_cet_etat"),
    commentaires: text(),
    service_id: text("service_id").notNull(),
  },
  (table) => [
    foreignKey({
      columns: [table.stateReportId],
      foreignColumns: [stateReport.id],
      name: "visited_section_state_report_id_fkey",
    }),
  ],
);

export const visitedSectionAttachment = pgTable("visited_section_attachment", {
  id: text().primaryKey().notNull(),
  isDeprecated: boolean("is_deprecated"),
  attachmentId: text("attachment_id").notNull(),
  visitedSectionId: text("visited_section_id").notNull(),
  label: text(),
  createdAt: timestamp("created_at", { mode: "string" }),
  service_id: text("service_id"),
});

export const userDept = pgTable(
  "user_dept",
  {
    userId: text("user_id").notNull(),
    deptNumber: text("dept_number").notNull(),
  },
  (table) => [
    foreignKey({
      columns: [table.userId],
      foreignColumns: [user.id],
      name: "user_dept_user_id_fkey",
    }).onDelete("cascade"),
    primaryKey({ columns: [table.userId, table.deptNumber], name: "user_dept_pkey" }),
  ],
);

export const merimeeToMemoire = pgTable(
  "merimee_to_memoire",
  {
    rowid: integer(),
    copy: text("COPY"),
    name: text("NAME"),
    refMemoire: text("REF_MEMOIRE").notNull(),
    refMerimee: text("REF_MERIMEE").notNull(),
    url: text("URL"),
  },
  (table) => [
    index("merimee_to_memoire_ref_merimee").using("btree", table.refMerimee.asc().nullsLast().op("text_ops")),
    primaryKey({ columns: [table.refMemoire, table.refMerimee], name: "merimee_to_memoire_pkey" }),
  ],
);
