version: "3.1"

volumes:
  pg_data:

services:
  frontend: 
    build: 
      context: .
      target: frontend

  backend:
    build:
      context: .
      target: backend
    environment: 
      PG_HOST: pg
      PG_PORT: ${PG_PORT}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_USERS_DB: ${PG_USERS_DB}
      JWT_SECRET: ${JWT_SECRET}
      ELECTRIC_SERVICE: http://electric
      ELECTRIC_PG_PROXY_PORT: ${PG_PROXY_PORT}
      HTTP_PORT: ${HTTP_PORT}
    depends_on:
      - electric

  pg:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_ELECTRIC_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PORT: ${PG_PORT}
      POSTGRES_MULTIPLE_DATABASES: ${PG_USERS_DB}
    command:
      - -c
      - wal_level=logical
    ports:
      - ${PG_PORT}:5432
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  electric:
    image: electricsql/electric:canary
    depends_on:
      - pg
    ports:
      - ${ELECTRIC_PORT}:5133
      - ${PG_PROXY_PORT}:65432
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - "${ADMINER_PORT:-8081}:8080"
