/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AtdatabasesMigrationsApplied {
  applied_at: Timestamp;
  id: Generated<Int8>;
  ignored_error: string | null;
  index: number;
  name: string;
  obsolete: boolean;
  script: string;
}

export interface AtdatabasesMigrationsVersion {
  id: number;
  version: string | null;
}

export interface ClauseV2 {
  id: string;
  key: string;
  position: number | null;
  text: string;
  udap_id: string | null;
  value: string;
}

export interface Delegation {
  createdBy: string;
  delegatedTo: string;
  id: string;
}

export interface InternalUser {
  email: string;
  id: string;
  password: string;
  role: string;
  temporaryLink: string | null;
  temporaryLinkExpiresAt: string | null;
  userId: string;
}

export interface Merimee {
  ACMH: string | null;
  ACTU: string | null;
  ACURL: string | null;
  ADRS: string | null;
  AFFE: string | null;
  AIRE: string | null;
  APPL: string | null;
  APRO: string | null;
  ARCHEO: string | null;
  AUTP: string | null;
  AUTR: string | null;
  BASE: string | null;
  CADA: string | null;
  CANT: string | null;
  COLL: string | null;
  COM: string | null;
  CONTACT: string | null;
  CONTIENT_IMAGE: string | null;
  COOR: string | null;
  COORM: string | null;
  COPY: string | null;
  COUV: string | null;
  DATE: string | null;
  DBOR: string | null;
  DENO: string | null;
  DENQ: string | null;
  DEPL: string | null;
  DESC: string | null;
  DIMS: string | null;
  DLAB: string | null;
  "DMAJ(DATE)": string | null;
  "DMIS(DATE)": string | null;
  DOMN: string | null;
  DOSADRS: string | null;
  DOSS: string | null;
  DOSURL: string | null;
  DOSURLPDF: string | null;
  DPRO: string | null;
  DPT: string | null;
  DPT_LETTRE: string | null;
  EDIF: string | null;
  ELEV: string | null;
  ENER: string | null;
  ESCA: string | null;
  ETAG: string | null;
  ETAT: string | null;
  ETUD: string | null;
  GENR: string | null;
  HIST: string | null;
  HYDR: string | null;
  IDAGR: string | null;
  IMAGE: string | null;
  IMG: string | null;
  IMPL: string | null;
  INSEE: string | null;
  INTE: string | null;
  JATT: string | null;
  JDAT: string | null;
  LIENS: string | null;
  LIEU: string | null;
  LINHA: string | null;
  LMDP: string | null;
  LOCA: string | null;
  LREG: string | null;
  MFICH: string | null;
  MHPP: string | null;
  MICR: string | null;
  MOSA: string | null;
  MURS: string | null;
  NBOR: string | null;
  NOMS: string | null;
  OBS: string | null;
  PAFF: string | null;
  PARN: string | null;
  PART: string | null;
  PDEN: string | null;
  PERS: string | null;
  PINT: string | null;
  PLAN: string | null;
  PLOC: string | null;
  POP_ARRETE_PROTECTION: string | null;
  POP_CONTIENT_GEOLOCALISATION: string | null;
  POP_COORDINATES_POINT: string | null;
  POP_COORDINATES_POLYGON: string | null;
  POP_COORDONNEES: string | null;
  POP_DATE: string | null;
  POP_DOSSIER_PROTECTION: string | null;
  POP_DOSSIER_VERT: string | null;
  POP_FLAGS: string | null;
  POP_HAS_LOCATION: string | null;
  POP_IMPORT: string | null;
  PPRO: string | null;
  PREP: string | null;
  PRODUCTEUR: string | null;
  PROT: string | null;
  PSTA: string | null;
  REF: string;
  REFE: string | null;
  REFIM: string | null;
  REFJOC: string | null;
  REFM: string | null;
  REFMUS: string | null;
  REFO: string | null;
  REFP: string | null;
  REG: string | null;
  REMA: string | null;
  REMP: string | null;
  RENV: string | null;
  REPR: string | null;
  RFPA: string | null;
  rowid: number | null;
  SCLD: string | null;
  SCLE: string | null;
  SCLX: string | null;
  SITE: string | null;
  STAT: string | null;
  TECH: string | null;
  THEM: string | null;
  TICO: string | null;
  TOIT: string | null;
  TOUT: string | null;
  TYPO: string | null;
  VERT: string | null;
  VIDEO: string | null;
  VISI: string | null;
  VOCA: string | null;
  VOUT: string | null;
  WADRS: string | null;
  WCOM: string | null;
  WEB: string | null;
  WRENV: string | null;
  ZONE: string | null;
}

export interface MerimeeToMemoire {
  COPY: string | null;
  NAME: string | null;
  REF_MEMOIRE: string;
  REF_MERIMEE: string;
  rowid: number | null;
  URL: string | null;
}

export interface PdfSnapshot {
  html: string | null;
  id: string;
  report: string | null;
  report_id: string | null;
  user_id: string | null;
}

export interface PictureLines {
  createdAt: Timestamp | null;
  id: string;
  lines: string;
  pictureId: string | null;
}

export interface Pictures {
  createdAt: Timestamp | null;
  finalUrl: string | null;
  id: string;
  reportId: string | null;
  url: string | null;
}

export interface PopImmeubles {
  adresse_forme_editoriale: string | null;
  adresse_forme_index: string | null;
  auteur_de_l_edifice: string | null;
  autre_appellation_de_l_edifice: string | null;
  cadastre: string | null;
  cadre_de_l_etude: string | null;
  cog_insee_lors_de_la_protection: string | null;
  commune_forme_editoriale: string | null;
  commune_forme_index: string | null;
  coordonnees_au_format_wgs84: string | null;
  copyright: string | null;
  couverts_ou_decouverts_du_jardin_de_l_edifice: string | null;
  datation_de_l_edifice: string | null;
  date_de_creation_de_la_notice: string | null;
  date_de_la_derniere_mise_a_jour: string | null;
  date_de_label: string | null;
  date_et_typologie_de_la_protection: string | null;
  denomination_de_l_edifice: string | null;
  "département": string | null;
  departement_format_numerique: string | null;
  description_de_l_edifice: string | null;
  description_de_l_elevation_interieure: string | null;
  description_de_l_iconographie: string | null;
  destination_actuelle_de_l_edifice: string | null;
  dimensions_normalisees_des_edicules_uniquement: string | null;
  domaine: string | null;
  elements_remarquables_dans_l_edifice: string | null;
  emplacement__forme_et_structure_de_l_escalier: string | null;
  etablissement_affectataire_de_l_edifice: string | null;
  etat_de_conservation: string | null;
  format_abrege_du_siecle_de_construction: string | null;
  genre_du_destinataire: string | null;
  historique: string | null;
  id: string | null;
  identifiant_agregee: string | null;
  indexation_iconographique_normalisee: string | null;
  justification_attribution: string | null;
  justification_de_la_datation: string | null;
  lien_vers_la_base_archiv_mh: string | null;
  lien_vers_la_base_joconde: string | null;
  lien_vers_la_base_palissy: string | null;
  liens_externes: string | null;
  lieu_de_conservation_d_un_element_architectural_deplace: string | null;
  lieudit: string | null;
  materiaux_de_la_couverture: string | null;
  materiaux_du_gros_oeuvre: string | null;
  nature_de_la_protection: string | null;
  nom_du_cours_d_eau_traversant_ou_bordant_l_edifice: string | null;
  observations: string | null;
  partie_constituante: string | null;
  partie_constituante_non_etudiee: string | null;
  partie_d_elevation_exterieure: string | null;
  personnes_liees_a_l_edifice: string | null;
  precision_affectataire: string | null;
  precision_de_la_localisation: string | null;
  precision_de_la_protection: string | null;
  precision_sur_la_denomination: string | null;
  precision_sur_le_statut_de_l_edifice: string | null;
  reference: string;
  reference_a_un_ensemble: string | null;
  references_des_parties_constituantes_etudiees: string | null;
  "région": string | null;
  remploi: string | null;
  renvoi_vers_une_notice_de_la_base_merimee_ou_palissy: string | null;
  siecle_de_campagne_secondaire_de_construction: string | null;
  siecle_de_la_campagne_principale_de_construction: string | null;
  source_de_l_energie_utilisee_par_l_edifice: string | null;
  statut_juridique_de_l_edifice: string | null;
  technique_du_decor_porte_de_l_edifice: string | null;
  titre_editorial_de_la_notice: string | null;
  type_de_couverture: string | null;
  typologie_de_la_protection: string | null;
  typologie_de_la_zone_de_protection: string | null;
  typologie_de_plan: string | null;
  typologie_du_couvrement: string | null;
  typologie_du_dossier: string | null;
  vocable___pour_les_edifices_cultuels: string | null;
}

export interface Report {
  applicantAddress: string | null;
  applicantEmail: string | null;
  applicantName: string | null;
  city: string | null;
  contacts: string | null;
  createdAt: Timestamp;
  createdBy: string;
  decision: string | null;
  disabled: boolean | null;
  furtherInformation: string | null;
  id: string;
  meetDate: Timestamp | null;
  pdf: string | null;
  precisions: string | null;
  projectCadastralRef: string | null;
  projectDescription: string | null;
  projectSpaceType: string | null;
  redactedBy: string | null;
  redactedById: string | null;
  serviceInstructeur: string | null;
  title: string | null;
  udap_id: string | null;
  zipCode: string | null;
}

export interface SentEmail {
  id: string;
  report_id: string | null;
  sent_at: Timestamp;
  sent_to: string;
  udap_id: string;
}

export interface ServiceInstructeurs {
  email: string | null;
  full_name: string;
  id: string;
  short_name: string;
  tel: string | null;
  udap_id: string | null;
}

export interface StateReport {
  adresse: string | null;
  code_postal: string | null;
  commune: string | null;
  commune_historique: string | null;
  description: string | null;
  id: string;
  nature_edifice: string | null;
  nature_protection: string | null;
  observations: string | null;
  parties_protegees: string | null;
  periode_construction: string | null;
  reference_cadastrale: string | null;
  reference_pop: string | null;
  udap_id: string;
}

export interface SuggestedEmail {
  email: string;
  id: string;
  udap_id: string;
}

export interface TmpPictures {
  createdAt: Timestamp | null;
  id: string;
  reportId: string | null;
}

export interface Transactions {
  created_at: Timestamp | null;
  data: string | null;
  entity_id: string;
  error: string | null;
  id: string;
  op: string;
  op_id: number;
  tx_id: number | null;
  type: string;
  user_id: string;
}

export interface Udap {
  address: string | null;
  city: string | null;
  completeCoords: string | null;
  department: string;
  dept_number: string | null;
  drac_text: string | null;
  email: string | null;
  id: string;
  marianne_text: string | null;
  name: string | null;
  phone: string | null;
  udap_text: string | null;
  visible: boolean | null;
  zipCode: string | null;
}

export interface User {
  email: string;
  id: string;
  name: string;
  udap_id: string;
}

export interface UserDept {
  dept_number: string;
  user_id: string;
}

export interface UserSettings {
  default_emails: string | null;
  id: string;
  udap_id: string | null;
  user_id: string | null;
}

export interface Whitelist {
  email: string;
}

export interface DB {
  atdatabases_migrations_applied: AtdatabasesMigrationsApplied;
  atdatabases_migrations_version: AtdatabasesMigrationsVersion;
  clause_v2: ClauseV2;
  delegation: Delegation;
  internal_user: InternalUser;
  merimee: Merimee;
  merimee_to_memoire: MerimeeToMemoire;
  pdf_snapshot: PdfSnapshot;
  picture_lines: PictureLines;
  pictures: Pictures;
  pop_immeubles: PopImmeubles;
  report: Report;
  sent_email: SentEmail;
  service_instructeurs: ServiceInstructeurs;
  state_report: StateReport;
  suggested_email: SuggestedEmail;
  tmp_pictures: TmpPictures;
  transactions: Transactions;
  udap: Udap;
  user: User;
  user_dept: UserDept;
  user_settings: UserSettings;
  whitelist: Whitelist;
}
