/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AtdatabasesMigrationsApplied {
  applied_at: Timestamp;
  id: Generated<Int8>;
  ignored_error: string | null;
  index: number;
  name: string;
  obsolete: boolean;
  script: string;
}

export interface AtdatabasesMigrationsVersion {
  id: number;
  version: string | null;
}

export interface ClauseV2 {
  id: string;
  key: string;
  position: number | null;
  text: string;
  udap_id: string | null;
  value: string;
}

export interface Delegation {
  createdBy: string;
  delegatedTo: string;
  id: string;
}

export interface InternalUser {
  email: string;
  id: string;
  password: string;
  role: string;
  temporaryLink: string | null;
  temporaryLinkExpiresAt: string | null;
  userId: string;
}

export interface Merimee {
  ACMH: string | null;
  ACTU: string | null;
  ACURL: string | null;
  ADRS: string | null;
  AFFE: string | null;
  AIRE: string | null;
  APPL: string | null;
  APRO: string | null;
  ARCHEO: string | null;
  AUTP: string | null;
  AUTR: string | null;
  BASE: string | null;
  CADA: string | null;
  CANT: string | null;
  COLL: string | null;
  COM: string | null;
  CONTACT: string | null;
  CONTIENT_IMAGE: string | null;
  COOR: string | null;
  COORM: string | null;
  COPY: string | null;
  COUV: string | null;
  DATE: string | null;
  DBOR: string | null;
  DENO: string | null;
  DENQ: string | null;
  DEPL: string | null;
  DESC: string | null;
  DIMS: string | null;
  DLAB: string | null;
  "DMAJ(DATE)": string | null;
  "DMIS(DATE)": string | null;
  DOMN: string | null;
  DOSADRS: string | null;
  DOSS: string | null;
  DOSURL: string | null;
  DOSURLPDF: string | null;
  DPRO: string | null;
  DPT: string | null;
  DPT_LETTRE: string | null;
  EDIF: string | null;
  ELEV: string | null;
  ENER: string | null;
  ESCA: string | null;
  ETAG: string | null;
  ETAT: string | null;
  ETUD: string | null;
  GENR: string | null;
  HIST: string | null;
  HYDR: string | null;
  IDAGR: string | null;
  IMAGE: string | null;
  IMG: string | null;
  IMPL: string | null;
  INSEE: string | null;
  INTE: string | null;
  JATT: string | null;
  JDAT: string | null;
  LIENS: string | null;
  LIEU: string | null;
  LINHA: string | null;
  LMDP: string | null;
  LOCA: string | null;
  LREG: string | null;
  MFICH: string | null;
  MHPP: string | null;
  MICR: string | null;
  MOSA: string | null;
  MURS: string | null;
  NBOR: string | null;
  NOMS: string | null;
  OBS: string | null;
  PAFF: string | null;
  PARN: string | null;
  PART: string | null;
  PDEN: string | null;
  PERS: string | null;
  PINT: string | null;
  PLAN: string | null;
  PLOC: string | null;
  POP_ARRETE_PROTECTION: string | null;
  POP_CONTIENT_GEOLOCALISATION: string | null;
  POP_COORDINATES_POINT: string | null;
  POP_COORDINATES_POLYGON: string | null;
  POP_COORDONNEES: string | null;
  POP_DATE: string | null;
  POP_DOSSIER_PROTECTION: string | null;
  POP_DOSSIER_VERT: string | null;
  POP_FLAGS: string | null;
  POP_HAS_LOCATION: string | null;
  POP_IMPORT: string | null;
  PPRO: string | null;
  PREP: string | null;
  PRODUCTEUR: string | null;
  PROT: string | null;
  PSTA: string | null;
  REF: string | null;
  REFE: string | null;
  REFIM: string | null;
  REFJOC: string | null;
  REFM: string | null;
  REFMUS: string | null;
  REFO: string | null;
  REFP: string | null;
  REG: string | null;
  REMA: string | null;
  REMP: string | null;
  RENV: string | null;
  REPR: string | null;
  RFPA: string | null;
  SCLD: string | null;
  SCLE: string | null;
  SCLX: string | null;
  SITE: string | null;
  STAT: string | null;
  TECH: string | null;
  THEM: string | null;
  TICO: string | null;
  TOIT: string | null;
  TOUT: string | null;
  TYPO: string | null;
  VERT: string | null;
  VIDEO: string | null;
  VISI: string | null;
  VOCA: string | null;
  VOUT: string | null;
  WADRS: string | null;
  WCOM: string | null;
  WEB: string | null;
  WRENV: string | null;
  ZONE: string | null;
}

export interface MerimeeToMemoire {
  COPY: string | null;
  NAME: string | null;
  REF_MEMOIRE: string | null;
  REF_MERIMEE: string | null;
  URL: string | null;
}

export interface PdfSnapshot {
  html: string | null;
  id: string;
  report: string | null;
  report_id: string | null;
  user_id: string | null;
}

export interface PictureLines {
  createdAt: Timestamp | null;
  id: string;
  lines: string;
  pictureId: string | null;
}

export interface Pictures {
  createdAt: Timestamp | null;
  finalUrl: string | null;
  id: string;
  reportId: string | null;
  url: string | null;
}

export interface Report {
  applicantAddress: string | null;
  applicantEmail: string | null;
  applicantName: string | null;
  city: string | null;
  contacts: string | null;
  createdAt: Timestamp;
  createdBy: string;
  decision: string | null;
  disabled: boolean | null;
  furtherInformation: string | null;
  id: string;
  meetDate: Timestamp | null;
  pdf: string | null;
  precisions: string | null;
  projectCadastralRef: string | null;
  projectDescription: string | null;
  projectSpaceType: string | null;
  redactedBy: string | null;
  redactedById: string | null;
  serviceInstructeur: string | null;
  title: string | null;
  udap_id: string | null;
  zipCode: string | null;
}

export interface SentEmail {
  id: string;
  report_id: string | null;
  sent_at: Timestamp;
  sent_to: string;
  udap_id: string;
}

export interface ServiceInstructeurs {
  email: string | null;
  full_name: string;
  id: string;
  short_name: string;
  tel: string | null;
  udap_id: string | null;
}

export interface StateReport {
  adresse: string | null;
  code_postal: string | null;
  commune: string | null;
  commune_historique: string | null;
  description: string | null;
  id: string;
  nature_edifice: string | null;
  nature_protection: string | null;
  observations: string | null;
  parties_protegees: string | null;
  periode_construction: string | null;
  reference_cadastrale: string | null;
  reference_pop: string | null;
}

export interface SuggestedEmail {
  email: string;
  id: string;
  udap_id: string;
}

export interface TmpPictures {
  createdAt: Timestamp | null;
  id: string;
  reportId: string | null;
}

export interface Transactions {
  created_at: Timestamp | null;
  data: string | null;
  entity_id: string;
  error: string | null;
  id: string;
  op: string;
  op_id: number;
  tx_id: number | null;
  type: string;
  user_id: string;
}

export interface Udap {
  address: string | null;
  city: string | null;
  completeCoords: string | null;
  department: string;
  dept_number: string | null;
  drac_text: string | null;
  email: string | null;
  id: string;
  marianne_text: string | null;
  name: string | null;
  phone: string | null;
  udap_text: string | null;
  visible: boolean | null;
  zipCode: string | null;
}

export interface User {
  email: string;
  id: string;
  name: string;
  udap_id: string;
}

export interface UserSettings {
  default_emails: string | null;
  id: string;
  udap_id: string | null;
  user_id: string | null;
}

export interface Whitelist {
  email: string;
}

export interface DB {
  atdatabases_migrations_applied: AtdatabasesMigrationsApplied;
  atdatabases_migrations_version: AtdatabasesMigrationsVersion;
  clause_v2: ClauseV2;
  delegation: Delegation;
  internal_user: InternalUser;
  merimee: Merimee;
  merimee_to_memoire: MerimeeToMemoire;
  pdf_snapshot: PdfSnapshot;
  picture_lines: PictureLines;
  pictures: Pictures;
  report: Report;
  sent_email: SentEmail;
  service_instructeurs: ServiceInstructeurs;
  state_report: StateReport;
  suggested_email: SuggestedEmail;
  tmp_pictures: TmpPictures;
  transactions: Transactions;
  udap: Udap;
  user: User;
  user_settings: UserSettings;
  whitelist: Whitelist;
}
