/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AtdatabasesMigrationsApplied {
  applied_at: Timestamp;
  id: Generated<Int8>;
  ignored_error: string | null;
  index: number;
  name: string;
  obsolete: boolean;
  script: string;
}

export interface AtdatabasesMigrationsVersion {
  id: number;
  version: string | null;
}

export interface ClauseV2 {
  id: string;
  key: string;
  position: number | null;
  text: string;
  udap_id: string | null;
  value: string;
}

export interface Delegation {
  createdBy: string;
  delegatedTo: string;
  id: string;
}

export interface InternalUser {
  email: string;
  id: string;
  password: string;
  role: string;
  temporaryLink: string | null;
  temporaryLinkExpiresAt: string | null;
  userId: string;
}

export interface PdfSnapshot {
  html: string | null;
  id: string;
  report: string | null;
  report_id: string | null;
  user_id: string | null;
}

export interface PictureLines {
  createdAt: Timestamp | null;
  id: string;
  lines: string;
  pictureId: string | null;
}

export interface Pictures {
  createdAt: Timestamp | null;
  finalUrl: string | null;
  id: string;
  reportId: string | null;
  url: string | null;
}

export interface Report {
  applicantAddress: string | null;
  applicantEmail: string | null;
  applicantName: string | null;
  city: string | null;
  contacts: string | null;
  createdAt: Timestamp;
  createdBy: string;
  decision: string | null;
  disabled: boolean | null;
  furtherInformation: string | null;
  id: string;
  meetDate: Timestamp | null;
  pdf: string | null;
  precisions: string | null;
  projectCadastralRef: string | null;
  projectDescription: string | null;
  projectSpaceType: string | null;
  redactedBy: string | null;
  redactedById: string | null;
  serviceInstructeur: string | null;
  title: string | null;
  udap_id: string | null;
  zipCode: string | null;
}

export interface SentEmail {
  id: string;
  report_id: string | null;
  sent_at: Timestamp;
  sent_to: string;
  udap_id: string;
}

export interface ServiceInstructeurs {
  email: string | null;
  full_name: string;
  id: string;
  short_name: string;
  tel: string | null;
  udap_id: string | null;
}

export interface SuggestedEmail {
  email: string;
  id: string;
  udap_id: string;
}

export interface TmpPictures {
  createdAt: Timestamp | null;
  id: string;
  reportId: string | null;
}

export interface Transactions {
  created_at: Timestamp | null;
  data: string | null;
  entity_id: string;
  error: string | null;
  id: string;
  op: string;
  op_id: number;
  tx_id: number | null;
  type: string;
  user_id: string;
}

export interface Udap {
  address: string | null;
  city: string | null;
  completeCoords: string | null;
  department: string;
  drac_text: string | null;
  email: string | null;
  id: string;
  marianne_text: string | null;
  name: string | null;
  phone: string | null;
  udap_text: string | null;
  visible: boolean | null;
  zipCode: string | null;
}

export interface User {
  id: string;
  name: string;
  udap_id: string;
}

export interface UserSettings {
  default_emails: string | null;
  id: string;
  user_id: string | null;
}

export interface Whitelist {
  email: string;
}

export interface DB {
  atdatabases_migrations_applied: AtdatabasesMigrationsApplied;
  atdatabases_migrations_version: AtdatabasesMigrationsVersion;
  clause_v2: ClauseV2;
  delegation: Delegation;
  internal_user: InternalUser;
  pdf_snapshot: PdfSnapshot;
  picture_lines: PictureLines;
  pictures: Pictures;
  report: Report;
  sent_email: SentEmail;
  service_instructeurs: ServiceInstructeurs;
  suggested_email: SuggestedEmail;
  tmp_pictures: TmpPictures;
  transactions: Transactions;
  udap: Udap;
  user: User;
  user_settings: UserSettings;
  whitelist: Whitelist;
}
