/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UdapImport } from './routes/udap'
import { Route as LoginImport } from './routes/login'
import { Route as AccountImport } from './routes/account'
import { Route as IndexImport } from './routes/index'
import { Route as ResetPasswordLinkImport } from './routes/reset-password.$link'
import { Route as PdfReportIdImport } from './routes/pdf.$reportId'
import { Route as EditReportIdImport } from './routes/edit.$reportId'

// Create Virtual Routes

const SignupLazyImport = createFileRoute('/signup')()
const ResetPasswordIndexLazyImport = createFileRoute('/reset-password/')()

// Create/Update Routes

const SignupLazyRoute = SignupLazyImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/signup.lazy').then((d) => d.Route))

const UdapRoute = UdapImport.update({
  path: '/udap',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AccountRoute = AccountImport.update({
  path: '/account',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordIndexLazyRoute = ResetPasswordIndexLazyImport.update({
  path: '/reset-password/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/reset-password.index.lazy').then((d) => d.Route),
)

const ResetPasswordLinkRoute = ResetPasswordLinkImport.update({
  path: '/reset-password/$link',
  getParentRoute: () => rootRoute,
} as any)

const PdfReportIdRoute = PdfReportIdImport.update({
  path: '/pdf/$reportId',
  getParentRoute: () => rootRoute,
} as any)

const EditReportIdRoute = EditReportIdImport.update({
  path: '/edit/$reportId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/account': {
      preLoaderRoute: typeof AccountImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/udap': {
      preLoaderRoute: typeof UdapImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      preLoaderRoute: typeof SignupLazyImport
      parentRoute: typeof rootRoute
    }
    '/edit/$reportId': {
      preLoaderRoute: typeof EditReportIdImport
      parentRoute: typeof rootRoute
    }
    '/pdf/$reportId': {
      preLoaderRoute: typeof PdfReportIdImport
      parentRoute: typeof rootRoute
    }
    '/reset-password/$link': {
      preLoaderRoute: typeof ResetPasswordLinkImport
      parentRoute: typeof rootRoute
    }
    '/reset-password/': {
      preLoaderRoute: typeof ResetPasswordIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AccountRoute,
  LoginRoute,
  UdapRoute,
  SignupLazyRoute,
  EditReportIdRoute,
  PdfReportIdRoute,
  ResetPasswordLinkRoute,
  ResetPasswordIndexLazyRoute,
])

/* prettier-ignore-end */
