/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServiceRouteImport } from './routes/service'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthCallbackRouteImport } from './routes/auth-callback'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PdfReportIdRouteImport } from './routes/pdf.$reportId'
import { Route as EditReportIdRouteImport } from './routes/edit.$reportId'
import { Route as ConstatConstatIdRouteImport } from './routes/constat.$constatId'
import { Route as ConstatConstatIdPdfRouteImport } from './routes/constat.$constatId.pdf'

const ServiceRoute = ServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth-callback',
  path: '/auth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfReportIdRoute = PdfReportIdRouteImport.update({
  id: '/pdf/$reportId',
  path: '/pdf/$reportId',
  getParentRoute: () => rootRouteImport,
} as any)
const EditReportIdRoute = EditReportIdRouteImport.update({
  id: '/edit/$reportId',
  path: '/edit/$reportId',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstatConstatIdRoute = ConstatConstatIdRouteImport.update({
  id: '/constat/$constatId',
  path: '/constat/$constatId',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstatConstatIdPdfRoute = ConstatConstatIdPdfRouteImport.update({
  id: '/pdf',
  path: '/pdf',
  getParentRoute: () => ConstatConstatIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/login': typeof LoginRoute
  '/service': typeof ServiceRoute
  '/constat/$constatId': typeof ConstatConstatIdRouteWithChildren
  '/edit/$reportId': typeof EditReportIdRoute
  '/pdf/$reportId': typeof PdfReportIdRoute
  '/constat/$constatId/pdf': typeof ConstatConstatIdPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/login': typeof LoginRoute
  '/service': typeof ServiceRoute
  '/constat/$constatId': typeof ConstatConstatIdRouteWithChildren
  '/edit/$reportId': typeof EditReportIdRoute
  '/pdf/$reportId': typeof PdfReportIdRoute
  '/constat/$constatId/pdf': typeof ConstatConstatIdPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/login': typeof LoginRoute
  '/service': typeof ServiceRoute
  '/constat/$constatId': typeof ConstatConstatIdRouteWithChildren
  '/edit/$reportId': typeof EditReportIdRoute
  '/pdf/$reportId': typeof PdfReportIdRoute
  '/constat/$constatId/pdf': typeof ConstatConstatIdPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/auth-callback'
    | '/login'
    | '/service'
    | '/constat/$constatId'
    | '/edit/$reportId'
    | '/pdf/$reportId'
    | '/constat/$constatId/pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth-callback'
    | '/login'
    | '/service'
    | '/constat/$constatId'
    | '/edit/$reportId'
    | '/pdf/$reportId'
    | '/constat/$constatId/pdf'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/auth-callback'
    | '/login'
    | '/service'
    | '/constat/$constatId'
    | '/edit/$reportId'
    | '/pdf/$reportId'
    | '/constat/$constatId/pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  LoginRoute: typeof LoginRoute
  ServiceRoute: typeof ServiceRoute
  ConstatConstatIdRoute: typeof ConstatConstatIdRouteWithChildren
  EditReportIdRoute: typeof EditReportIdRoute
  PdfReportIdRoute: typeof PdfReportIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/service': {
      id: '/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-callback': {
      id: '/auth-callback'
      path: '/auth-callback'
      fullPath: '/auth-callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf/$reportId': {
      id: '/pdf/$reportId'
      path: '/pdf/$reportId'
      fullPath: '/pdf/$reportId'
      preLoaderRoute: typeof PdfReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit/$reportId': {
      id: '/edit/$reportId'
      path: '/edit/$reportId'
      fullPath: '/edit/$reportId'
      preLoaderRoute: typeof EditReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/constat/$constatId': {
      id: '/constat/$constatId'
      path: '/constat/$constatId'
      fullPath: '/constat/$constatId'
      preLoaderRoute: typeof ConstatConstatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/constat/$constatId/pdf': {
      id: '/constat/$constatId/pdf'
      path: '/pdf'
      fullPath: '/constat/$constatId/pdf'
      preLoaderRoute: typeof ConstatConstatIdPdfRouteImport
      parentRoute: typeof ConstatConstatIdRoute
    }
  }
}

interface ConstatConstatIdRouteChildren {
  ConstatConstatIdPdfRoute: typeof ConstatConstatIdPdfRoute
}

const ConstatConstatIdRouteChildren: ConstatConstatIdRouteChildren = {
  ConstatConstatIdPdfRoute: ConstatConstatIdPdfRoute,
}

const ConstatConstatIdRouteWithChildren =
  ConstatConstatIdRoute._addFileChildren(ConstatConstatIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  LoginRoute: LoginRoute,
  ServiceRoute: ServiceRoute,
  ConstatConstatIdRoute: ConstatConstatIdRouteWithChildren,
  EditReportIdRoute: EditReportIdRoute,
  PdfReportIdRoute: PdfReportIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
