/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CreateImport } from './routes/create'
import { Route as IndexImport } from './routes/index'
import { Route as ExportReportIdImport } from './routes/export.$reportId'
import { Route as EditReportIdImport } from './routes/edit.$reportId'

// Create Virtual Routes

const SignupLazyImport = createFileRoute('/signup')()
const LoginLazyImport = createFileRoute('/login')()
const ResetPasswordIndexLazyImport = createFileRoute('/reset-password/')()
const ResetPasswordLinkLazyImport = createFileRoute('/reset-password/$link')()

// Create/Update Routes

const SignupLazyRoute = SignupLazyImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/signup.lazy').then((d) => d.Route))

const LoginLazyRoute = LoginLazyImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const CreateRoute = CreateImport.update({
  path: '/create',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordIndexLazyRoute = ResetPasswordIndexLazyImport.update({
  path: '/reset-password/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/reset-password.index.lazy').then((d) => d.Route),
)

const ResetPasswordLinkLazyRoute = ResetPasswordLinkLazyImport.update({
  path: '/reset-password/$link',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/reset-password.$link.lazy').then((d) => d.Route),
)

const ExportReportIdRoute = ExportReportIdImport.update({
  path: '/export/$reportId',
  getParentRoute: () => rootRoute,
} as any)

const EditReportIdRoute = EditReportIdImport.update({
  path: '/edit/$reportId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/create': {
      preLoaderRoute: typeof CreateImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      preLoaderRoute: typeof SignupLazyImport
      parentRoute: typeof rootRoute
    }
    '/edit/$reportId': {
      preLoaderRoute: typeof EditReportIdImport
      parentRoute: typeof rootRoute
    }
    '/export/$reportId': {
      preLoaderRoute: typeof ExportReportIdImport
      parentRoute: typeof rootRoute
    }
    '/reset-password/$link': {
      preLoaderRoute: typeof ResetPasswordLinkLazyImport
      parentRoute: typeof rootRoute
    }
    '/reset-password/': {
      preLoaderRoute: typeof ResetPasswordIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  CreateRoute,
  LoginLazyRoute,
  SignupLazyRoute,
  EditReportIdRoute,
  ExportReportIdRoute,
  ResetPasswordLinkLazyRoute,
  ResetPasswordIndexLazyRoute,
])

/* prettier-ignore-end */
