version: "3.1"

volumes:
  pg_data_preprod:

services:
  frontend:
    image: ghcr.io/betagouv/compte-rendu-vif-development:frontend
    restart: always
    depends_on:
      - electric

  backend:
    image: ghcr.io/betagouv/compte-rendu-vif-development:backend
    restart: always
    depends_on:
      - electric

  pg:
    image: postgres:14-alpine
    command:
      - -c
      - wal_level=logical
    restart: always
    volumes:
      - pg_data_preprod:/var/lib/postgresql/data

  electric:
    image: electricsql/electric:0.12.0
    restart: always
    depends_on:
      - pg

  adminer:
    image: adminer
    restart: always
