version: "3.1"

volumes:
  pg_data:

services:
  frontend:
    image: ghcr.io/betagouv/compte-rendu-vif-main:frontend
    restart: always
    depends_on:
      - electric

  backend:
    image: ghcr.io/betagouv/compte-rendu-vif-main:backend
    restart: always
    depends_on:
      - electric

  pg:
    image: postgres:14-alpine
    command:
      - -c
      - wal_level=logical
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db/init/:/docker-entrypoint-initdb.d

  electric:
    image: electricsql/electric:0.11.1
    depends_on:
      - pg
    restart: always

  adminer:
    image: adminer
    restart: always
